a_core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("analytics/", include("analytics.urls")),
]

if settings.MAINTENANCE:
    urlpatterns += [
        path(
            "",
            TemplateView.as_view(template_name="maintenance.html"),
            name="maintenance",
        )
    ]
else:
    urlpatterns += [
        path("accounts/", include("allauth.urls")),
        path("", include("accounts.urls")),
        path("", include("a_contacts.urls")),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

analytics/urls.py
from django.urls import path

from . import views

app_name = "analytics"
urlpatterns = [
    path("like/", views.like_view, name="like"),
    path("likescount/", views.get_likes_count_view, name="get-likes-count"),
    path("liveusers/", views.live_users_view, name="live-users"),
]

analytics/models.py
from django.db import models


class Like(models.Model):
    ip_address = models.GenericIPAddressField(unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"liked at {self.created_at.astimezone()}"

analytics/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render

from .middleware import LiveUsersMiddleware
from .models import Like


def like_view(request):
    ip = get_client_ip(request)
    if not Like.objects.filter(ip_address=ip).exists():
        Like.objects.create(ip_address=ip)
    likes_count = Like.objects.count()
    return HttpResponse(likes_count)


def get_likes_count_view(request):
    likes_count = Like.objects.count()
    return HttpResponse(likes_count)


def get_client_ip(request):
    x_forwarded_for = request.META.get("HTTP_X_FORWARDED_FOR")
    if x_forwarded_for:
        ip = x_forwarded_for.split(",")[0]
    else:
        ip = request.META.get("REMOTE_ADDR")
    return ip


def live_users_view(request):
    live_users = LiveUsersMiddleware.get_active_user_count()
    return render(request, "partials/live_user_count.html", {"live_users": live_users})

templates/analytics/likes.html
{% load static %}
<img class="h-6 cursor-pointer transition-transform duration-300 active:scale-90" src="{% static 'img/heart.svg' %}" alt="like-heart"
  hx-get="{% url 'analytics:like' %}" hx-trigger="click" hx-target="#likes-count" hx-swap="innerHTML" title="Did you like the project?">
<span class="font-sans font-extrabold">Likes:
  <span hx-get="{% url 'analytics:get-likes-count' %}" hx-trigger="load" hx-swap="innerHTML" id="likes-count">0</span>
</span>

templates/analytics/live_users.html
{% load static %}
<img class="h-6 cursor-pointer transition-transform duration-300 active:scale-90" src="{% static 'img/user.svg' %}" alt="user-icon"
  hx-get="{% url 'analytics:live-users' %}" hx-trigger="load, click" hx-target="#live-users-count" hx-swap="outerHTML" title="refresh?">
<span id="live-users-count" class="font-sans font-extrabold">0 Users Online </span>