a_contacts/urls.py
from django.urls import path

from . import views

app_name = "a_contacts"

urlpatterns = [
    path("", views.homePageView, name="home"),
    path("dashboard/", views.DashboardView.as_view(), name="dashboard"),
    path("contact/create/", views.ContactCreateView.as_view(), name="contact-create"),
    path(
        "contact/bulkcreate/", views.contactBulkCreateView, name="contact-bulk-create"
    ),
    path(
        "contact/bulkcreate/preview/",
        views.contactBulkCreatePreview,
        name="contact-bulk-create-preview",
    ),
    path(
        "contact/<uuid:pk>/", views.ContactDetailView.as_view(), name="contact-detail"
    ),
    path(
        "contact/<uuid:pk>/update/",
        views.ContactUpdateView.as_view(),
        name="contact-update",
    ),
    path("contact/<uuid:pk>/delete/", views.contactDeleteView, name="contact-delete"),
    path(
        "contact/<uuid:pk>/restore/", views.contactRestoreView, name="contact-restore"
    ),
    path("contact/create/fake/", views.fillContactForm, name="fake-contact-create"),
    path(
        "contact/bulkcreate/fake/",
        views.exportRandomDataCSV,
        name="export-fake-csv-data",
    ),
    path("contact/export/csv", views.exportDataCSV, name="export-data-csv"),
    path("contact/export/pdf", views.exportDataPDF, name="export-data-pdf"),
    path("events/", views.EventListView.as_view(), name="event-list"),
]

a_core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("analytics/", include("analytics.urls")),
]

if settings.MAINTENANCE:
    urlpatterns += [
        path(
            "",
            TemplateView.as_view(template_name="maintenance.html"),
            name="maintenance",
        )
    ]
else:
    urlpatterns += [
        path("accounts/", include("allauth.urls")),
        path("", include("accounts.urls")),
        path("", include("a_contacts.urls")),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("employee/approval-status/", views.approval_status, name="approval_status"),
    path("employees/", views.EmployeeListView.as_view(), name="employee-list"),
    path(
        "employee/<uuid:pk>/",
        views.EmployeeDetailView.as_view(),
        name="employee-detail",
    ),
    path(
        "employee/<uuid:pk>/update/",
        views.EmployeeUpdateView.as_view(),
        name="employee-update",
    ),
    path(
        "employee/<uuid:pk>/delete/",
        views.employeeDeleteView,
        name="employee-delete",
    ),
]

templates/partials/contact_bulk_create_modal_form.html
{% load templatetags %}
{% load static %}
<div id="modal" class="p-4 md:p-5 text-center">
  <!-- <svg class="mx-auto mb-4 text-gray-400 w-12 h-12" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
      d="M10 11V6m0 8h.01M19 10a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
  </svg> -->
  <svg class="mx-auto mb-4 text-gray-400 w-12 h-12" aria-hidden="true" viewBox="0 0 400 400" xmlns="http://www.w3.org/2000/svg">

    <defs>

      <style>
        .cls-1 {
          fill: #101010;
        }
      </style>

    </defs>

    <title />

    <g id="xxx-word">

      <path class="cls-1" d="M325,105H250a5,5,0,0,1-5-5V25a5,5,0,1,1,10,0V95h70a5,5,0,0,1,0,10Z" />

      <path class="cls-1"
        d="M325,154.83a5,5,0,0,1-5-5V102.07L247.93,30H100A20,20,0,0,0,80,50v98.17a5,5,0,0,1-10,0V50a30,30,0,0,1,30-30H250a5,5,0,0,1,3.54,1.46l75,75A5,5,0,0,1,330,100v49.83A5,5,0,0,1,325,154.83Z" />

      <path class="cls-1"
        d="M300,380H100a30,30,0,0,1-30-30V275a5,5,0,0,1,10,0v75a20,20,0,0,0,20,20H300a20,20,0,0,0,20-20V275a5,5,0,0,1,10,0v75A30,30,0,0,1,300,380Z" />

      <path class="cls-1" d="M275,280H125a5,5,0,1,1,0-10H275a5,5,0,0,1,0,10Z" />

      <path class="cls-1" d="M200,330H125a5,5,0,1,1,0-10h75a5,5,0,0,1,0,10Z" />

      <path class="cls-1"
        d="M325,280H75a30,30,0,0,1-30-30V173.17a30,30,0,0,1,30-30h.2l250,1.66a30.09,30.09,0,0,1,29.81,30V250A30,30,0,0,1,325,280ZM75,153.17a20,20,0,0,0-20,20V250a20,20,0,0,0,20,20H325a20,20,0,0,0,20-20V174.83a20.06,20.06,0,0,0-19.88-20l-250-1.66Z" />

      <path class="cls-1"
        d="M168.48,217.48l8.91,1a20.84,20.84,0,0,1-6.19,13.18q-5.33,5.18-14,5.18-7.31,0-11.86-3.67a23.43,23.43,0,0,1-7-10,37.74,37.74,0,0,1-2.46-13.87q0-12.19,5.78-19.82t15.9-7.64a18.69,18.69,0,0,1,13.2,4.88q5.27,4.88,6.64,14l-8.91.94q-2.46-12.07-10.86-12.07-5.39,0-8.38,5t-3,14.55q0,9.69,3.2,14.63t8.48,4.94a9.3,9.3,0,0,0,7.19-3.32A13.25,13.25,0,0,0,168.48,217.48Z" />

      <path class="cls-1"
        d="M179.41,223.15l9.34-2q1.68,7.93,12.89,7.93,5.12,0,7.87-2a6.07,6.07,0,0,0,2.75-5,7.09,7.09,0,0,0-1.25-4q-1.25-1.85-5.35-2.91l-10.2-2.66a25.1,25.1,0,0,1-7.73-3.11,12.15,12.15,0,0,1-4-4.9,15.54,15.54,0,0,1-1.5-6.76,14,14,0,0,1,5.31-11.46q5.31-4.32,13.59-4.32a24.86,24.86,0,0,1,12.29,3,13.56,13.56,0,0,1,6.89,8.52l-9.14,2.27q-2.11-6.05-9.84-6.05-4.49,0-6.86,1.88a5.83,5.83,0,0,0-2.36,4.77q0,4.57,7.42,6.41l9.06,2.27q8.24,2.07,11.05,6.11a15.29,15.29,0,0,1,2.81,8.93,14.7,14.7,0,0,1-5.92,12.36q-5.92,4.51-15.33,4.51a28,28,0,0,1-13.89-3.32A16.29,16.29,0,0,1,179.41,223.15Z" />

      <path class="cls-1" d="M250.31,236h-9.77L224.1,182.68h10.16l12.23,40.86L259,182.68h8Z" />

    </g>

  </svg>
  <h3 class="text-lg font-normal text-gray-500">Upload .csv file</h3>

  <form class="my-4" enctype="multipart/form-data" hx-post="{% url 'a_contacts:contact-bulk-create'%}" hx-target="#modal"
    hx-swap="outerHTML">
    {% csrf_token %}
    <div class="mb-4">
      {{ form.csv_file }}
      {{ form.csv_file.errors }}
    </div>
    <div class="flex flex-row items-start justify-between">
      <div>
        <button type="submit"
          class="select-none w-[80px] text-white bg-primary-400 hover:bg-primary-500 focus:outline-none font-medium rounded-lg text-sm border border-primary-400 hover:border-primary-500 px-4 py-2 text-center transition-transform duration-300 active:scale-95">
          Upload
        </button>
        <a @click="showModal = false"
          class="cursor-pointer select-none w-[80px] inline-flex items-center justify-center text-center py-2 px-4 ms-3 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 focus:z-10 transition-transform duration-300 active:scale-95">Cancel</a>
      </div>
      <a href="{% url 'a_contacts:export-fake-csv-data' %}"><img src="{% static 'img/dice.svg' %}" title="Want Random Data?"
          class="inline-block ml-4 h-8 select-none transition-transform duration-300 hover:scale-125 active:scale-95">
        </img>
      </a>
    </div>
  </form>
</div>

templates/partials/contact_create_form.html
{% load static %}
<div id="contact-create-form" class="grid gap-4 sm:grid-cols-2 sm:gap-6">
  <div class="sm:col-span-2 flex flex-col sm:flex-row gap-4 sm:justify-between">
    <div class="flex flex-col items-center ">
      <label for="profile-image" class="block w-fit mb-2 text-sm font-medium text-gray-900">Profile Image</label>
      <img id="profile-image" class="w-20 h-20 border border-gray-500 object-cover rounded-full bg-primary"
        src="{% static 'img/image-placeholder.png' %}" alt="Profile Image">
    </div>
    <div class="flex flex-col justify-end">
      <label class="block mb-2 text-sm font-medium text-gray-900 sm:text-right" for="file_input">Upload image</label>
      {{ form.image }}
      <p class="mt-1 text-xs text-gray-500 text-right" id="file_input_help">Supports only PNG, JPG or WEBP files.</p>
    </div>
  </div>
  <div class="w-full">
    <label for="first-name" class="block mb-2 text-sm font-medium text-gray-900 ">First Name</label>
    {{ form.first_name }}
  </div>
  <div class="w-full">
    <label for="last-name" class="block mb-2 text-sm font-medium text-gray-900 ">Last Name</label>
    {{ form.last_name }}
  </div>
  <div class="sm:col-span-2">
    <label for="email" class="block mb-2 text-sm font-medium text-gray-900 ">Email</label>
    {{ form.email }}
  </div>
  <div class="w-full">
    <label for="location" class="block mb-2 text-sm font-medium text-gray-900 ">Location</label>
    {{ form.location }}
  </div>
  <div>
    <label for="type" class="block mb-2 text-sm font-medium text-gray-900 ">Type</label>
    {{ form.type }}
  </div>
</div>

templates/partials/contact_delete_confirm.html
{% load templatetags %}
<div id="modal" class="p-4 md:p-5 text-center">
  <svg class="mx-auto mb-4 text-gray-400 w-12 h-12" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
      d="M10 11V6m0 8h.01M19 10a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
  </svg>
  <h3 class="text-lg font-normal text-gray-500">Are you sure you want to delete this contact?</h3>
  <p class="mb-5">{{contact}} ({{contact.contact_id|format_contact_id}})</p>

  {% if dashboard %}
  <form hx-post="{% url 'a_contacts:contact-delete' contact.pk %}" hx-target="#contact-{{ contact.contact_id }}"
    hx-swap="outerHTML swap:1s">
    {% else %}
    <form action="{% url 'a_contacts:contact-delete' contact.pk %}" method="post">
      {% endif%}
      {% csrf_token %}
      <button @click="showModal = false" type="submit"
        class="select-none w-[80px] text-white bg-red-400 hover:bg-red-500 focus:outline-none font-medium rounded-lg text-sm  border  border-red-400 hover:border-red-500 px-4 py-2 text-center transition-transform duration-300 active:scale-95">
        Delete
      </button>
      <a @click="showModal = false"
        class="cursor-pointer select-none w-[80px] inline-flex items-center justify-center text-center py-2 px-4 ms-3 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 focus:z-10 transition-transform duration-300 active:scale-95">Cancel</a>
    </form>
</div>

templates/partials/contact_form.html
{% load static %}
<div id="contact-form" class="grid gap-4 sm:grid-cols-2 sm:gap-6">
  <div x-data="{
      fileInput: null,
      image: null,
      previewImage(event) {
        const file = event.target.files[0];
        if (file && file.type.includes('image')) {
          const url = URL.createObjectURL(file);
          this.image.src = url;
        }
      }
    }" x-init="fileInput = $refs.fileInput; image = $refs.profileImage"
    class="sm:col-span-2 flex flex-col sm:flex-row gap-4 sm:justify-between">
    <div class="flex flex-col items-center">
      <label for="profile-image" class="block w-max mb-2 text-sm font-medium text-gray-900">Profile Image</label>
      <img x-ref="profileImage" id="profile-image" class="w-20 h-20 border border-gray-500 object-cover rounded-full bg-primary"
        alt="Profile Image" {% if contact and contact.image %} src="{{ contact.image.url }}" {% else %}
        src="{% static 'img/image-placeholder.png' %}" {% endif %}>
    </div>
    <div class="flex flex-col justify-end w-full">
      <label class="block mb-2 text-sm font-medium text-gray-900 sm:text-right" for="file_input">Upload image</label>
      {{ form.image }}
      {{ form.image.errors }}
      <p class="mt-1 text-xs text-gray-500 text-right" id="file_input_help">Supports only PNG, JPG or WEBP files.</p>
    </div>
  </div>
  <div class="w-full">
    <label for="first-name" class="block mb-2 text-sm font-medium text-gray-900 ">First Name</label>
    {{ form.first_name }}
    {{ form.first_name.errors }}
  </div>
  <div class="w-full">
    <label for="last-name" class="block mb-2 text-sm font-medium text-gray-900 ">Last Name</label>
    {{ form.last_name }}
    {{ form.last_name.errors }}
  </div>
  <div class="sm:col-span-2">
    <label for="email" class="block mb-2 text-sm font-medium text-gray-900 ">Email</label>
    {{ form.email }}
    {{ form.email.errors }}
  </div>
  <div class="w-full">
    <label for="location" class="block mb-2 text-sm font-medium text-gray-900 ">Location</label>
    {{ form.location }}
  </div>
  <div>
    <label for="type" class="block mb-2 text-sm font-medium text-gray-900 ">Type</label>
    {{ form.type }}
  </div>
</div>

templates/partials/contact_restore_confirm.html
{% load templatetags %}
<div id="modal" class="p-4 md:p-5 text-center">
  <svg class="mx-auto mb-4 text-gray-400 w-12 h-12" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
      d="M10 11V6m0 8h.01M19 10a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
  </svg>
  <h3 class="text-lg font-normal text-gray-500">Are you sure you want to restore this contact?</h3>
  <p class="mb-5">{{contact}} ({{contact.contact_id|format_contact_id}})</p>

  <form action="{% url 'a_contacts:contact-restore' contact.pk %}" method="post">
    {% csrf_token %}
    <button @click="showModal = false" type="submit"
      class="select-none w-[80px] text-white bg-green-400 hover:bg-green-500 focus:outline-none font-medium rounded-lg text-sm  border  border-green-400 hover:border-green-500 px-4 py-2 text-center transition-transform duration-300 active:scale-95">
      Restore
    </button>
    <a @click="showModal = false"
      class="cursor-pointer select-none w-[80px] inline-flex items-center justify-center text-center py-2 px-4 ms-3 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 focus:z-10 transition-transform duration-300 active:scale-95">Cancel</a>
  </form>

</div>

templates/partials/live_user_count.html
<span id="live-users-count" class="font-sans font-extrabold">
  {{ live_users }} User{{ live_users|pluralize }} Online
</span>

templates/partials/table_row.html
{% load templatetags %}
{% load static %}
{% if is_result %}
{% for contact in contacts %}
<tr class="border-b hover:bg-gray-100" id="contact-{{contact.contact_id}}">
  <td class="hidden w-4 sm:table-cell px-4 py-3">{{ forloop.counter|add:page_offset }}</td>
  <td class=" max-w-8 px-4 py-3">{{ contact.contact_id|format_contact_id }}</td>
  <th scope="row" class="flex items-center gap-2 max-w-60 px-4 py-3 font-medium text-gray-900 whitespace-nowrap ">
    {% if contact.image %}
    <img class="rounded-full h-10 w-10 border border-gray-300 object-cover hidden sm:block" src="{{ contact.image_thumbnail.url }}" alt="">
    {% else %}
    <img class="rounded-full h-10 w-10 border border-gray-300 object-cover hidden sm:block" src="{% static 'img/image-placeholder.png' %}"
      alt="">
    {% endif %}
    <a class="truncate" href="{% url 'a_contacts:contact-detail' contact.id %}">{{contact}}</a>
  </th>
  <td class="hidden max-w-28 sm:table-cell px-4 py-3 truncate">{{contact.email}}</td>
  <td class="hidden max-w-16 lg:table-cell px-4 py-3 truncate">{{contact.location}}</td>
  <td class="w-8 px-4 py-3">
    <span
      class="inline-flex items-center rounded {% if contact.type == 'LEAD' %}bg-blue-200 text-blue-800{% elif contact.type == 'PROSPECT' %}bg-yellow-200 text-yellow-800{% else %}bg-green-200 text-green-800{% endif %} px-2.5 py-0.5 text-xs font-medium">
      {{contact.type}}
    </span>
  </td>
  <td x-data="{dropdownOpen: false}" @click.away="dropdownOpen = false" class="relative px-4 py-3 flex items-center justify-end">
    <button @click="dropdownOpen = !dropdownOpen"
      class="flex items-center text-sm font-medium text-center text-gray-500 hover:text-gray-800 hover:bg-gray-300 rounded-lg "
      type="button">
      <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
        <path d="M6 10a2 2 0 11-4 0 2 2 0 014 0zM12 10a2 2 0 11-4 0 2 2 0 014 0zM16 12a2 2 0 100-4 2 2 0 000 4z" />
      </svg>
    </button>
    <div x-show="dropdownOpen" x-cloak
      class="absolute top-11 z-10 w-40 p-2 bg-gray-50 rounded-lg divide-y divide-gray-200 shadow select-none"
      x-transition:enter="duration-300 ease-out" x-transition:enter-start="opacity-0 -translate-y-5 scale-90"
      x-transition:enter-end="opacity-100 translate-y-0 scale-100" x-transition:leave="duration-300 ease-out"
      x-transition:leave-start="opacity-100 translate-y-0" x-transition:leave-end="opacity-0 -translate-y-5">
      <ul class="menulist pb-1 text-sm text-gray-700" aria-labelledby="dropdown-button">
        <li>
          <a @click="dropdownOpen = false" href="{% url 'a_contacts:contact-detail' contact.pk %}" class="">View</a>
        </li>
        <li>
          <a @click="dropdownOpen = false" href="{% url 'a_contacts:contact-update' contact.pk %}" class="">Edit</a>
        </li>
      </ul>
      <div class="menulist pt-1">
        <a hx-get="{% url 'a_contacts:contact-delete' contact.pk %}" hx-target="#modal" hx-swap="outerHTML"
          @click="showModal = true, dropdownOpen = false" class="text-sm text-gray-700 hover:bg-red-200">Delete</a>
      </div>
    </div>
  </td>
</tr>
{% endfor%}
{% if more_contacts %}
<tr hx-get="{% url 'a_contacts:dashboard' %}?page={{next_page}}" hx-indicator="#spinner" hx-trigger="revealed" hx-swap="outerHTML"
  hx-include="#filter-form, #search-form, #sort-form">
</tr>
{% endif %}
{% else %}
<tr class="border-b hover:bg-gray-100">
  <th scope="row" colspan="7" class="text-center px-4 py-3 font-bold text-xl text-gray-900 whitespace-nowrap truncate ">
    No Contacts Found
  </th>
</tr>
{% endif %}

templates/partials/user_delete_confirm.html
<div id="modal" class="p-4 md:p-5 text-center">
  <svg class="mx-auto mb-4 text-gray-400 w-12 h-12" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
      d="M10 11V6m0 8h.01M19 10a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
  </svg>
  <h3 class="text-lg font-normal text-gray-500">Are you sure you want to delete your user account?</h3>
  <p class="mb-5">{{user}} ({{user.employee_id}})</p>
  <form action="{% url 'accounts:employee-delete' user.pk %}" method="post">
    {% csrf_token %}
    <button @click="showModal = false" type="submit"
      class="select-none w-[80px] text-white bg-red-400 hover:bg-red-500 focus:outline-none font-medium rounded-lg text-sm  border  border-red-400 hover:border-red-500 px-4 py-2 text-center transition-transform duration-300 active:scale-95">
      Delete
    </button>
    <a @click="showModal = false"
      class="cursor-pointer select-none w-[80px] inline-flex items-center justify-center text-center py-2 px-4 ms-3 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 focus:z-10 transition-transform duration-300 active:scale-95">Cancel</a>
  </form>
</div>