a_contacts/urls.py
from django.urls import path

from . import views

app_name = "a_contacts"

urlpatterns = [
    path("", views.homePageView, name="home"),
    path("dashboard/", views.DashboardView.as_view(), name="dashboard"),
    path("contact/create/", views.ContactCreateView.as_view(), name="contact-create"),
    path(
        "contact/bulkcreate/", views.contactBulkCreateView, name="contact-bulk-create"
    ),
    path(
        "contact/bulkcreate/preview/",
        views.contactBulkCreatePreview,
        name="contact-bulk-create-preview",
    ),
    path(
        "contact/<uuid:pk>/", views.ContactDetailView.as_view(), name="contact-detail"
    ),
    path(
        "contact/<uuid:pk>/update/",
        views.ContactUpdateView.as_view(),
        name="contact-update",
    ),
    path("contact/<uuid:pk>/delete/", views.contactDeleteView, name="contact-delete"),
    path(
        "contact/<uuid:pk>/restore/", views.contactRestoreView, name="contact-restore"
    ),
    path("contact/create/fake/", views.fillContactForm, name="fake-contact-create"),
    path(
        "contact/bulkcreate/fake/",
        views.exportRandomDataCSV,
        name="export-fake-csv-data",
    ),
    path("contact/export/csv", views.exportDataCSV, name="export-data-csv"),
    path("contact/export/pdf", views.exportDataPDF, name="export-data-pdf"),
    path("events/", views.EventListView.as_view(), name="event-list"),
]

a_core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("analytics/", include("analytics.urls")),
]

if settings.MAINTENANCE:
    urlpatterns += [
        path(
            "",
            TemplateView.as_view(template_name="maintenance.html"),
            name="maintenance",
        )
    ]
else:
    urlpatterns += [
        path("accounts/", include("allauth.urls")),
        path("", include("accounts.urls")),
        path("", include("a_contacts.urls")),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

a_contacts/forms.py
from django import forms
from django.forms import FileInput, ModelForm, Select, TextInput

from .models import Contact
from .utils.validators import validate_csv_file_extension


class ContactForm(ModelForm):
    error_css_class = "error"

    class Meta:
        model = Contact
        fields = "__all__"
        widgets = {
            "first_name": TextInput(
                attrs={
                    "id": "first-name",
                    "class": "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:border-primary-500 block w-full p-2.5",
                }
            ),
            "last_name": TextInput(
                attrs={
                    "id": "last-name",
                    "class": "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:border-primary-500 block w-full p-2.5",
                }
            ),
            "email": TextInput(
                attrs={
                    "id": "email",
                    "class": "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:border-primary-500 block w-full p-2.5",
                }
            ),
            "location": TextInput(
                attrs={
                    "id": "location",
                    "class": "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:border-primary-500 block w-full p-2.5",
                }
            ),
            "type": Select(
                attrs={
                    "id": "type",
                    "class": "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:border-primary-500 block w-full p-2.5",
                }
            ),
            "image": FileInput(
                attrs={
                    "id": "image-input",
                    "class": "block w-full text-sm text-gray-900 border border-gray-300 p-1.5 rounded-lg cursor-pointer bg-gray-50 focus:outline-none",
                    "x-ref": "fileInput",
                    "@change": "previewImage($event)",
                }
            ),
        }


class ContactBulkCreateForm(forms.Form):
    csv_file = forms.FileField(
        validators=[validate_csv_file_extension],
        required=True,
        widget=forms.FileInput(
            attrs={
                "class": "block w-full text-sm text-gray-900 border border-gray-300 p-1.5 rounded-lg cursor-pointer bg-gray-50 focus:outline-none"
            }
        ),
    )

a_contacts/views.py
import csv
import random
import urllib

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.db.models import Q
from django.http import Http404, HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import CreateView, DetailView, ListView, UpdateView
from faker import Faker

from analytics.models import Like

from .forms import ContactBulkCreateForm, ContactForm
from .mixins import MessageMixin
from .models import Contact, Event
from .templatetags.templatetags import format_contact_id
from .utils.utils import get_active_object_or_404


def homePageView(request):
    if request.user.is_authenticated:
        return redirect("a_contacts:dashboard")
    else:
        return render(request, "home.html")


class DashboardView(LoginRequiredMixin, ListView):
    model = Contact
    search_text = ""
    selected_filters = []
    is_result = True
    is_search_text = False
    context_object_name = "contacts"
    template_name = "a_contacts/dashboard.html"
    paginate_by = 20
    sort_by = None
    order = None

    def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        self.sort_by = request.GET.get("sort-radio")
        self.order = request.GET.get("order-radio")
        self.selected_filters = request.GET.getlist("type")
        self.search_text = request.GET.get("search_text", "")
        if self.search_text:
            self.search_text = urllib.parse.unquote(self.search_text)
            self.search_text = self.search_text.strip()
            self.is_search_text = True
        return super().get(request, *args, **kwargs)

    def render_to_response(self, context, **response_kwargs):
        response_kwargs.setdefault("content_type", self.content_type)

        if self.request.headers.get("Hx-Request"):
            return self.response_class(
                request=self.request,
                template="partials/table_row.html",
                context=context,
                using=self.template_engine,
                **response_kwargs,
            )
        else:
            return self.response_class(
                request=self.request,
                template=self.get_template_names(),
                context=context,
                using=self.template_engine,
                **response_kwargs,
            )

    def get_queryset(self):
        search_text_length = len(self.search_text)

        if self.selected_filters:
            contacts = Contact.active_objects.filter(type__in=self.selected_filters)

        else:
            contacts = Contact.active_objects.all()

        if self.sort_by:
            if self.order == "asc":
                contacts = contacts.order_by(self.sort_by)
            else:
                contacts = contacts.order_by(f"-{self.sort_by}")

        if self.search_text and search_text_length > 3:
            if self.search_text.startswith("#"):
                q = self.search_text[1:].lstrip("0")

                if q.isdigit():
                    id_length = len(q)
                else:
                    self.is_result = False
                    return Contact.active_objects.none()
                if (id_length in (1, 2) and search_text_length == 4) or (
                    id_length >= 3 and search_text_length == id_length + 1
                ):
                    queryset = contacts.filter(contact_id=q)
                else:
                    self.is_result = False
                    return Contact.active_objects.none()

            else:
                parts = self.search_text.split()

                q = (
                    Q(first_name__icontains=parts[0])
                    | Q(last_name__icontains=parts[0])
                    | Q(email__icontains=parts[0])
                    | Q(location__icontains=parts[0])
                    | Q(type__icontains=parts[0])
                )
                for part in parts[1:]:
                    q |= (
                        Q(first_name__icontains=part)
                        | Q(last_name__icontains=part)
                        | Q(email__icontains=part)
                        | Q(location__icontains=part)
                        | Q(type__icontains=part)
                    )
                queryset = contacts.filter(q)

            if queryset:
                return queryset
            else:
                self.is_result = False
                return Contact.active_objects.none()
        else:
            return contacts

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_result"] = self.is_result
        context["is_search_text"] = self.is_search_text

        if self.is_result and context.get("page_obj"):
            page_obj = context["page_obj"]
            context["page_offset"] = (page_obj.number - 1) * self.paginate_by
            context["more_contacts"] = page_obj.has_next()
            if page_obj.has_next():
                context["next_page"] = page_obj.next_page_number()
            else:
                context["next_page"] = None
        else:
            context["page_offset"] = 0
            context["more_contacts"] = False
            context["next_page"] = None
            context["contacts"] = []

        context["lead_count"] = Contact.active_objects.filter(type="LEAD").count()
        context["prospect_count"] = Contact.active_objects.filter(
            type="PROSPECT"
        ).count()
        context["customer_count"] = Contact.active_objects.filter(
            type="CUSTOMER"
        ).count()
        context["manager_count"] = (
            get_user_model().objects.filter(role="MANAGER").count()
        )
        context["agent_count"] = get_user_model().objects.filter(role="AGENT").count()
        context["search_text"] = self.search_text
        context["selected_filters"] = self.selected_filters
        context["likes"] = Like.objects.count()

        return context


class ContactCreateView(LoginRequiredMixin, MessageMixin, CreateView):
    form_class = ContactForm
    template_name = "a_contacts/contact_create.html"
    success_message = "Contact created successfully"
    error_message = "Failed to create contact"

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.updated_by = self.request.user
        return super().form_valid(form)


@login_required
def fillContactForm(request):
    faker = Faker()
    fake_name = faker.name()
    while fake_name.split()[0].endswith("."):
        fake_name = faker.name()

    first_name = fake_name.split()[0]
    last_name = fake_name.split()[1]
    types = [Contact.Type.LEAD, Contact.Type.PROSPECT, Contact.Type.CUSTOMER]

    fake_contact = {
        "first_name": first_name,
        "last_name": last_name,
        "email": f"{first_name.lower()}.{last_name.lower()}@email.com",
        "location": faker.country(),
        "type": random.choice(types),
    }
    form = ContactForm(initial=fake_contact)

    return render(request, "partials/contact_form.html", {"form": form})


class ContactUpdateView(LoginRequiredMixin, MessageMixin, UpdateView):
    model = Contact
    form_class = ContactForm
    context_object_name = "contact"
    template_name = "a_contacts/contact_update.html"
    success_message = "Contact updated successfully"
    error_message = "Failed to update contact"

    def form_valid(self, form):
        form.instance.updated_by = self.request.user
        form.instance.last_action = Event.Action.UPDATE
        return super().form_valid(form)

    def get_queryset(self):
        return Contact.active_objects.all()


class ContactDetailView(LoginRequiredMixin, DetailView):
    model = Contact
    context_object_name = "contact"
    template_name = "a_contacts/contact_detail.html"

    def get_queryset(self):
        return Contact.active_objects.all()


@login_required
def contactBulkCreateView(request):
    if request.method == "GET" and request.headers.get("Hx-Request"):
        form = ContactBulkCreateForm()
        return render(
            request, "partials/contact_bulk_create_modal_form.html", {"form": form}
        )
    elif request.method == "POST" and request.FILES.get("csv_file"):
        form = ContactBulkCreateForm(request.POST, request.FILES)
        if form.is_valid():
            csv_file = form.cleaned_data["csv_file"]
            decoded_file = csv_file.read().decode("utf-8").splitlines()
            csv_reader = csv.DictReader(decoded_file)
            valid_data = []
            invalid_data = []

            for row in csv_reader:
                try:
                    obj = Contact(**row)
                    obj.full_clean()
                    valid_data.append(row)
                except ValidationError as e:
                    row["errors"] = e.message_dict
                    invalid_data.append(row)

            request.session["preview_data"] = valid_data
            request.session["invalid_data"] = invalid_data

            return JsonResponse({"redirect": "/contact/bulkcreate/preview/"})
        else:
            return render(
                request, "partials/contact_bulk_create_modal_form.html", {"form": form}
            )
    else:
        return redirect("a_contacts:dashboard")


@login_required
def contactBulkCreatePreview(request):
    valid_data = request.session.get("preview_data", [])
    invalid_data = request.session.get("invalid_data", [])
    user = request.user

    if request.method == "POST":
        for row in valid_data:
            Contact.objects.create(
                first_name=row["first_name"],
                last_name=row["last_name"],
                email=row["email"],
                location=row["location"],

templates/a_contacts/contact_create.html
{% extends 'layouts/b.html' %}
{% load static %}

{% block title %}Create Contact -{% endblock title %}

{% block content %}
<section class="bg-white ">
  <div class="py-8 sm:py-16 px-4 mx-auto max-w-2xl ">
    <div class="flex flex-row items-center justify-between mb-8">
      <h2 class="text-2xl font-bold text-gray-900 ">Create Contact</h2>
      <a @click="showModal = true" hx-get="{% url 'a_contacts:contact-bulk-create'%}" hx-target="#modal" hx-swap="outerHTML"
        class="cursor-pointer font-medium text-sm text-primary-500 hover:underline select-none">
        Bulk Upload ?
      </a>
    </div>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% include 'partials/contact_form.html' %}
      <button type="submit"
        class="w-[80px]  px-4 py-2 mt-4 sm:mt-6 text-sm font-medium text-center text-white bg-primary-500 rounded-lg hover:bg-primary-700 select-none transition-transform duration-300 active:scale-95">
        Save
      </button>
      <a class="w-[80px] justify-center inline-flex items-center px-4 py-2 ml-2 mt-4 sm:mt-6 text-sm font-medium text-center text-white bg-red-400 rounded-lg hover:bg-red-500 select-none transition-transform duration-300 active:scale-95"
        href="{{ request.META.HTTP_REFERER }}">Cancel</a>
      <img src="{% static 'img/dice.svg' %}" title="Fill Random Data?" hx-get="{% url 'a_contacts:fake-contact-create' %}"
        hx-target="#contact-form" hx-swap="outerHTML"
        class="inline-block ml-4 h-8 select-none transition-transform duration-300 hover:scale-125 active:scale-95">
      </img>
    </form>
  </div>
</section>
{% endblock content%}

templates/a_contacts/contact_detail.html
{% extends 'layouts/b.html' %}
{% load templatetags %}
{% load static %}

{% block title %}View Contact -{% endblock title %}

{% block content %}
<section class="bg-white">
  <div class="py-8 mx-auto md:max-w-[70%] md:py-16 flex flex-col md:flex-row items-center justify-between gap-10">
    <div class="w-1/3">
      {% if contact.image %}
      <img class="object-contain border border-gray-300 size-fit" src="{{ contact.image.url }}" alt="">
      {% else %}
      <img class="object-contain border border-gray-300 size-fit" src="{% static 'img/image-placeholder.png' %}" alt="">
      {% endif %}
    </div>
    <div class="w-2/3">
      <h2 class="mb-2 text-xl font-semibold leading-none text-gray-900 md:text-2xl ">{{ contact }}</h2>
      <p class="mb-4 text-base font-normal leading-none text-gray-700 ">{{ contact.contact_id|format_contact_id }}</p>
      <hr>
      <dl class="mt-4">
        <dt class="mb-2 font-semibold leading-none text-gray-900">Email</dt>
        <dd class="mb-4 font-light text-gray-500 sm:mb-5">{{ contact.email }}</dd>
      </dl>
      <dl class="flex items-center justify-between space-x-6">
        <div>
          <dt class="mb-2 font-semibold leading-none text-gray-900 ">Type</dt>
          <dd
            class="mb-4 text-sm font-medium px-2.5 py-0.5 rounded {% if contact.type == 'LEAD' %}bg-blue-200 text-blue-800{% elif contact.type == 'PROSPECT' %}bg-yellow-200 text-yellow-800{% else %}bg-green-200 text-green-800{% endif %} sm:mb-5 ">
            {{ contact.type }}</dd>
        </div>
        <div>
          <dt class="mb-2 font-semibold leading-none text-gray-900 text-right">Location</dt>
          <dd class="mb-4 font-light text-gray-500 sm:mb-5 text-right">{{ contact.location }}</dd>
        </div>
      </dl>
      <dl class="flex items-center justify-between space-x-6">
        <div>
          <dt class="mb-2 font-semibold leading-none text-gray-900 ">Created by</dt>
          <dd
            class="mb-4 font-light text-gray-500 sm:mb-5">
            {% if contact.created_by %}
            {{ contact.created_by.username }}
            {% else %}
            No Data Found
            {% endif %}
          </dd>
        </div>
        <div>
          <dt class="mb-2 font-semibold leading-none text-gray-900 text-right">Created at</dt>
          <dd class="mb-4 font-light text-gray-500 sm:mb-5 text-right">{{ contact.created_at }}</dd>
        </div>
      </dl>
      <dl class="flex items-center justify-between space-x-6">
        <div>
          <dt class="mb-2 font-semibold leading-none text-gray-900 ">Last Updated by</dt>
          <dd class="mb-4 font-light text-gray-500 sm:mb-5">
            {% if contact.updated_by %}
            {{ contact.updated_by.username }}
            {% else %}
            No Data Found
            {% endif %}
          </dd>
        </div>
        <div>
          <dt class="mb-2 font-semibold leading-none text-gray-900 text-right">Last Updated at</dt>
          <dd class="mb-4 font-light text-gray-500 sm:mb-5 text-right">{{ contact.updated_at }}</dd>
        </div>
      </dl>
      <div class="flex items-center space-x-4">
        <a href="{% url 'a_contacts:contact-update' contact.pk %}"
          class="w-[80px] text-white inline-flex justify-center items-center bg-primary-500 hover:bg-primary-700 select-none font-medium rounded-lg text-sm px-4 py-2 text-center transition-transform duration-300 active:scale-95">
          Edit
        </a>
        <a @click="showModal = true" hx-get="{% url 'a_contacts:contact-delete' contact.pk %}" hx-target="#modal" hx-swap="outerHTML"
          class="w-[80px] inline-flex cursor-pointer items-center justify-center text-white bg-red-400 hover:bg-red-500 select-none font-medium rounded-lg text-sm px-4 py-2 text-center transition-transform duration-300 active:scale-95">
          Delete
        </a>
      </div>
    </div>
  </div>
</section>
{% endblock content%}

templates/a_contacts/contact_update.html
{% extends 'layouts/b.html' %}
{% load static %}

{% block title %}Update Contact -{% endblock title %}

{% block content %}
<section class="bg-white ">
  <div class="py-8 px-4 mx-auto max-w-2xl sm:py-16">
    <h2 class="mb-8 text-2xl font-bold text-gray-900 ">Update Contact</h2>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% include 'partials/contact_form.html' %}
      <button type="submit"
        class=" w-[80px] justify-center inline-flex items-center px-4 py-2 mt-4 sm:mt-6 text-sm font-medium text-center text-white bg-primary-500 rounded-lg hover:bg-primary-700 select-none transition-transform duration-300 active:scale-95">
        Save
      </button>
      <a class="w-[80px] justify-center inline-flex items-center px-4 py-2 ml-2 mt-4 sm:mt-6 text-sm font-medium text-center text-white bg-red-400 rounded-lg hover:bg-red-500 select-none transition-transform duration-300 active:scale-95"
        href="{{ request.META.HTTP_REFERER }}">Cancel</a>
    </form>
  </div>
</section>
{% endblock content%}

templates/a_contacts/main.html
{% extends 'layouts/a.html' %}
{% load templatetags %}

{% block content %}

<div class="bg-white relative sm:rounded-lg overflow-hidden">
  <div class="flex flex-col md:flex-row items-center justify-between space-y-3 md:space-y-0 md:space-x-4 p-4">
    <div class="w-full md:w-1/2">
      <form class="flex items-center">
        <label for="simple-search" class="sr-only">Search</label>
        <div class="relative w-full">
          <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
            <svg aria-hidden="true" class="w-5 h-5 text-gray-500 " fill="currentColor" viewbox="0 0 20 20"
              xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd"
                d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                clip-rule="evenodd" />
            </svg>
          </div>
          <input type="text" id="simple-search" 
            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:border-primary-500 block w-full pl-10 p-2"
            placeholder="Search" required="">
        </div>
      </form>
    </div>
    <div
      class="w-full md:w-auto flex flex-col md:flex-row space-y-2 md:space-y-0 items-stretch md:items-center justify-end md:space-x-3 flex-shrink-0">
      <div x-data="{dropdownOpen: false}" @click.away="dropdownOpen = false" class="relative flex items-center space-x-3 w-full md:w-auto">
        <a href="{% url 'a_contacts:contact-create' %}" class="w-full md:w-auto">
          <button @click="dropdownOpen = false" type="button"
          class="w-full md:w-auto justify-center inline-flex items-center px-4 py-2 text-sm font-medium text-center text-white bg-primary-500 rounded-lg hover:bg-primary-700
          select-none transition-transform duration-300 active:scale-95">
          <!-- class="w-full flex items-center justify-center text-white bg-primary-500 hover:bg-primary-700 font-medium rounded-lg text-sm px-4 py-2 transition-transform duration-300 active:scale-95"> -->
            <svg class="h-3.5 w-3.5 mr-2" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
              <path clip-rule="evenodd" fill-rule="evenodd"
                d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" />
            </svg>
            Add Contact
          </button>
        </a>
        <button @click="dropdownOpen = !dropdownOpen"
          class="w-full md:w-auto flex items-center justify-center py-2 px-4 text-sm font-medium text-gray-900 bg-gray-50 rounded-lg border border-gray-200 hover:bg-gray-100 focus:z-10"
          type="button">
          <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" class="h-4 w-4 mr-2 " viewbox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd"
              d="M3 3a1 1 0 011-1h12a1 1 0 011 1v3a1 1 0 01-.293.707L12 11.414V15a1 1 0 01-.293.707l-2 2A1 1 0 018 17v-5.586L3.293 6.707A1 1 0 013 6V3z"
              clip-rule="evenodd" />
          </svg>
          Filter
          <svg class="-mr-1 ml-1.5 w-5 h-5" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
            <path clip-rule="evenodd" fill-rule="evenodd"
              d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" />
          </svg>
        </button>
        <div x-show="dropdownOpen" x-cloak class="absolute  top-12 right-0 z-10 w-40 p-2 bg-gray-50 rounded-lg shadow"
          x-transition:enter="duration-300 ease-out" x-transition:enter-start="opacity-0 -translate-y-5 scale-90"
          x-transition:enter-end="opacity-100 translate-y-0 scale-100" x-transition:leave="duration-300 ease-out"
          x-transition:leave-start="opacity-100 translate-y-0" x-transition:leave-end="opacity-0 -translate-y-5">
          <ul class="space-y-2 text-sm select-none" aria-labelledby="filterDropdownButton">
            <li class="flex items-center">
              <input id="lead" type="checkbox" value="" class="w-4 h-4 border-gray-300 rounded-lg">
              <label for="lead" class="ml-2 text-sm p-2 text-gray-700 ">Leads (56)</label>
            </li>
            <li class="flex items-center">
              <input id="prospect" type="checkbox" value="" class="w-4 h-4  border-gray-300 rounded-lg">
              <label for="prospect" class="ml-2 text-sm p-2 text-gray-700">Prospects (16)</label>
            </li>
            <li class="flex items-center">
              <input id="customer" type="checkbox" value="" class="w-4 h-4  border-gray-300 rounded-lg">
              <label for="customer" class="ml-2 text-sm p-2 text-gray-700 ">Customers (49)</label>
            </li>
          </ul>
        </div>

      </div>
    </div>
  </div>
  <div class="overflow-x-auto">
    <table class="w-full text-sm text-left text-gray-500 mb-40">
      <thead class="text-xs text-gray-700 uppercase bg-gray-200 ">
        <tr>
          <th scope="col" class="hidden sm:table-cell px-4 py-3">S.No.</th>
          <th scope="col" class="px-4 py-3">ID</th>
          <th scope="col" class="px-4 py-3">Name</th>
          <th scope="col" class="hidden sm:table-cell px-4 py-3">Email</th>
          <th scope="col" class="hidden lg:table-cell px-4 py-3">Location</th>
          <th scope="col" class="px-4 py-3">Type</th>
          <th scope="col" class="px-4 py-3">
            <span class="sr-only">Actions</span>
          </th>
        </tr>
      </thead>
      <tbody>
        {% for contact in contacts %}
        <tr class="border-b hover:bg-gray-100">
          <td class="hidden sm:table-cell px-4 py-3">{{forloop.counter}}</td>
          <td class="px-4 py-3">{{ contact.contact_id|format_contact_id }}</td>
          <th scope="row" class="w-full max-w-0 sm:max-w-none sm:w-auto px-4 py-3 font-medium text-gray-900 whitespace-nowrap truncate ">
            <a href="{% url 'a_contacts:contact-detail' contact.id %}">{{contact}}</a></th>
          <td class="hidden sm:max-w-40 sm:table-cell px-4 py-3 truncate">{{contact.email}}</td>
          <td class="hidden lg:max-w-30 lg:table-cell px-4 py-3 truncate">{{contact.location}}</td>
          <td class="px-4 py-3">
            <span
              class="inline-flex items-center rounded {% if contact.type == 'LEAD' %}bg-blue-200 text-blue-800{% elif contact.type == 'PROSPECT' %}bg-yellow-200 text-yellow-800{% else %}bg-green-200 text-green-800{% endif %} px-2.5 py-0.5 text-xs font-medium">
              {{contact.type}}
            </span>
          </td>
          <td x-data="{dropdownOpen: false}" @click.away="dropdownOpen = false" class="relative px-4 py-3 flex items-center justify-end">
            <button @click="dropdownOpen = !dropdownOpen"
              class="relative inline-flex items-center p-0.5 text-sm font-medium text-center text-gray-500 hover:text-gray-800 hover:bg-gray-300 rounded-lg "
              type="button">
              <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                <path d="M6 10a2 2 0 11-4 0 2 2 0 014 0zM12 10a2 2 0 11-4 0 2 2 0 014 0zM16 12a2 2 0 100-4 2 2 0 000 4z" />
              </svg>
            </button>
            <div x-show="dropdownOpen" x-cloak
              class="absolute top-11 z-10 w-40 p-2 bg-gray-50 rounded-lg divide-y divide-gray-200 shadow select-none"
              x-transition:enter="duration-300 ease-out" x-transition:enter-start="opacity-0 -translate-y-5 scale-90"
              x-transition:enter-end="opacity-100 translate-y-0 scale-100" x-transition:leave="duration-300 ease-out"
              x-transition:leave-start="opacity-100 translate-y-0" x-transition:leave-end="opacity-0 -translate-y-5">
              <ul class="menulist pb-1 text-sm text-gray-700" aria-labelledby="dropdown-button">
                <li>
                  <a href="{% url 'a_contacts:contact-detail' contact.pk %}" class="">View</a>
                </li>
                <li>
                  <a href="{% url 'a_contacts:contact-update' contact.pk %}" class="">Edit</a>
                </li>
              </ul>
              <div class="menulist pt-1">
                <a href="#" class="text-sm text-gray-700 hover:bg-red-200">Delete</a>
              </div>
            </div>
          </td>
        </tr>
        {% endfor%}
      </tbody>
    </table>
  </div>

</div>

{% endblock content%}