a_contacts/urls.py
from django.urls import path

from . import views

app_name = "a_contacts"

urlpatterns = [
    path("", views.homePageView, name="home"),
    path("dashboard/", views.DashboardView.as_view(), name="dashboard"),
    path("contact/create/", views.ContactCreateView.as_view(), name="contact-create"),
    path(
        "contact/bulkcreate/", views.contactBulkCreateView, name="contact-bulk-create"
    ),
    path(
        "contact/bulkcreate/preview/",
        views.contactBulkCreatePreview,
        name="contact-bulk-create-preview",
    ),
    path(
        "contact/<uuid:pk>/", views.ContactDetailView.as_view(), name="contact-detail"
    ),
    path(
        "contact/<uuid:pk>/update/",
        views.ContactUpdateView.as_view(),
        name="contact-update",
    ),
    path("contact/<uuid:pk>/delete/", views.contactDeleteView, name="contact-delete"),
    path(
        "contact/<uuid:pk>/restore/", views.contactRestoreView, name="contact-restore"
    ),
    path("contact/create/fake/", views.fillContactForm, name="fake-contact-create"),
    path(
        "contact/bulkcreate/fake/",
        views.exportRandomDataCSV,
        name="export-fake-csv-data",
    ),
    path("contact/export/csv", views.exportDataCSV, name="export-data-csv"),
    path("contact/export/pdf", views.exportDataPDF, name="export-data-pdf"),
    path("events/", views.EventListView.as_view(), name="event-list"),
]

a_core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("analytics/", include("analytics.urls")),
]

if settings.MAINTENANCE:
    urlpatterns += [
        path(
            "",
            TemplateView.as_view(template_name="maintenance.html"),
            name="maintenance",
        )
    ]
else:
    urlpatterns += [
        path("accounts/", include("allauth.urls")),
        path("", include("accounts.urls")),
        path("", include("a_contacts.urls")),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("employee/approval-status/", views.approval_status, name="approval_status"),
    path("employees/", views.EmployeeListView.as_view(), name="employee-list"),
    path(
        "employee/<uuid:pk>/",
        views.EmployeeDetailView.as_view(),
        name="employee-detail",
    ),
    path(
        "employee/<uuid:pk>/update/",
        views.EmployeeUpdateView.as_view(),
        name="employee-update",
    ),
    path(
        "employee/<uuid:pk>/delete/",
        views.employeeDeleteView,
        name="employee-delete",
    ),
]

templates/includes/features.html
<section class="">
  <div class="py-8 px-4 mx-auto max-w-screen-xl sm:py-16 lg:px-6">
    <!-- <div class="max-w-screen-md mb-8 lg:mb-16">
      <h2 class="mb-4 text-4xl tracking-tight font-extrabold text-gray-900">Designed for business teams like yours</h2>
      <p class="text-gray-500 sm:text-xl">Here at Flowbite we focus on markets where technology, innovation, and capital
        can unlock long-term value and drive economic growth.</p>
    </div> -->
    <div class="space-y-8 md:grid md:grid-cols-2 lg:grid-cols-3 md:gap-12 md:space-y-0">
      <div class="bg-white p-4 rounded-lg">
        <div class="flex justify-center items-center mb-4 w-10 h-10 rounded-full bg-primary-100 lg:h-12 lg:w-12">
          <svg class="w-6 h-6 text-primary-600"  aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24"
            fill="currentColor" viewBox="0 0 24 24">
            <path fill-rule="evenodd"
              d="M12 20a7.966 7.966 0 0 1-5.002-1.756l.002.001v-.683c0-1.794 1.492-3.25 3.333-3.25h3.334c1.84 0 3.333 1.456 3.333 3.25v.683A7.966 7.966 0 0 1 12 20ZM2 12C2 6.477 6.477 2 12 2s10 4.477 10 10c0 5.5-4.44 9.963-9.932 10h-.138C6.438 21.962 2 17.5 2 12Zm10-5c-1.84 0-3.333 1.455-3.333 3.25S10.159 13.5 12 13.5c1.84 0 3.333-1.455 3.333-3.25S13.841 7 12 7Z"
              clip-rule="evenodd" />
          </svg>
        </div>
        <h3 class="mb-2 text-xl font-bold">Contact Management</h3>
        <p class="text-gray-500">Easily manage contacts with advanced search, filtering, and sorting options.</p>
      </div>
      <div class="bg-white p-4 rounded-lg">
        <div class="flex justify-center items-center mb-4 w-10 h-10 rounded-full bg-primary-100 lg:h-12 lg:w-12">
          <svg class="w-6 h-6 text-primary-600" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24"
            fill="currentColor" viewBox="0 0 24 24">
            <path fill-rule="evenodd"
              d="M12 6a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7Zm-1.5 8a4 4 0 0 0-4 4 2 2 0 0 0 2 2h7a2 2 0 0 0 2-2 4 4 0 0 0-4-4h-3Zm6.82-3.096a5.51 5.51 0 0 0-2.797-6.293 3.5 3.5 0 1 1 2.796 6.292ZM19.5 18h.5a2 2 0 0 0 2-2 4 4 0 0 0-4-4h-1.1a5.503 5.503 0 0 1-.471.762A5.998 5.998 0 0 1 19.5 18ZM4 7.5a3.5 3.5 0 0 1 5.477-2.889 5.5 5.5 0 0 0-2.796 6.293A3.501 3.501 0 0 1 4 7.5ZM7.1 12H6a4 4 0 0 0-4 4 2 2 0 0 0 2 2h.5a5.998 5.998 0 0 1 3.071-5.238A5.505 5.505 0 0 1 7.1 12Z"
              clip-rule="evenodd" />
          </svg>
        </div>
        <h3 class="mb-2 text-xl font-bold">Multi-user Support</h3>
        <p class="text-gray-500">Collaborate effectively with support for multiple user accounts and roles.</p>
      </div>
      <div class="bg-white p-4 rounded-lg">
        <div class="flex justify-center items-center mb-4 w-10 h-10 rounded-full bg-primary-100 lg:h-12 lg:w-12">
          <svg class="w-6 h-6 text-primary-600" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
            viewBox="0 0 24 24">
            <path fill-rule="evenodd"
              d="M8 10V7a4 4 0 1 1 8 0v3h1a2 2 0 0 1 2 2v7a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2v-7a2 2 0 0 1 2-2h1Zm2-3a2 2 0 1 1 4 0v3h-4V7Zm2 6a1 1 0 0 1 1 1v3a1 1 0 1 1-2 0v-3a1 1 0 0 1 1-1Z"
              clip-rule="evenodd" />
          </svg>
        </div>
        <h3 class="mb-2 text-xl font-bold">Role-based Access Control (RBAC)</h3>
        <p class="text-gray-500">Granular control over user roles and permissions within the CRM.</p>
      </div>
      <div class="bg-white p-4 rounded-lg">
        <div class="flex justify-center items-center mb-4 w-10 h-10 rounded-full bg-primary-100 lg:h-12 lg:w-12">
          <svg class="w-6 h-6 text-primary-600" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none"
            viewBox="0 0 24 24">
            <path stroke="currentColor" stroke-linecap="round" stroke-width="2" d="M9 8h10M9 12h10M9 16h10M4.99 8H5m-.02 4h.01m0 4H5" />
          </svg>
        </div>
        <h3 class="mb-2 text-xl font-bold">Events System</h3>
        <p class="text-gray-500">Track and review major user actions like create, update, and delete.</p>
      </div>
      <div class="bg-white p-4 rounded-lg">
        <div class="flex justify-center items-center mb-4 w-10 h-10 rounded-full bg-primary-100 lg:h-12 lg:w-12">
          <svg class="w-6 h-6 text-primary-600" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24"
            fill="currentColor" viewBox="0 0 24 24">
            <path fill-rule="evenodd"
              d="M9 2.221V7H4.221a2 2 0 0 1 .365-.5L8.5 2.586A2 2 0 0 1 9 2.22ZM11 2v5a2 2 0 0 1-2 2H4a2 2 0 0 0-2 2v7a2 2 0 0 0 2 2 2 2 0 0 0 2 2h12a2 2 0 0 0 2-2 2 2 0 0 0 2-2v-7a2 2 0 0 0-2-2V4a2 2 0 0 0-2-2h-7Zm1.018 8.828a2.34 2.34 0 0 0-2.373 2.13v.008a2.32 2.32 0 0 0 2.06 2.497l.535.059a.993.993 0 0 0 .136.006.272.272 0 0 1 .263.367l-.008.02a.377.377 0 0 1-.018.044.49.49 0 0 1-.078.02 1.689 1.689 0 0 1-.297.021h-1.13a1 1 0 1 0 0 2h1.13c.417 0 .892-.05 1.324-.279.47-.248.78-.648.953-1.134a2.272 2.272 0 0 0-2.115-3.06l-.478-.052a.32.32 0 0 1-.285-.341.34.34 0 0 1 .344-.306l.94.02a1 1 0 1 0 .043-2l-.943-.02h-.003Zm7.933 1.482a1 1 0 1 0-1.902-.62l-.57 1.747-.522-1.726a1 1 0 0 0-1.914.578l1.443 4.773a1 1 0 0 0 1.908.021l1.557-4.773Zm-13.762.88a.647.647 0 0 1 .458-.19h1.018a1 1 0 1 0 0-2H6.647A2.647 2.647 0 0 0 4 13.647v1.706A2.647 2.647 0 0 0 6.647 18h1.018a1 1 0 1 0 0-2H6.647A.647.647 0 0 1 6 15.353v-1.706c0-.172.068-.336.19-.457Z"
              clip-rule="evenodd" />
          </svg>
        </div>
        <h3 class="mb-2 text-xl font-bold">Bulk Data Handling</h3>
        <p class="text-gray-500">Seamless bulk upload, preview, and creation of contacts from CSV files.</p>
      </div>
      <div class="bg-white p-4 rounded-lg">
        <div class="flex justify-center items-center mb-4 w-10 h-10 rounded-full bg-primary-100 lg:h-12 lg:w-12">
          <svg class="w-6 h-6 text-primary-600" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24"
            fill="currentColor" viewBox="0 0 24 24">
            <path fill-rule="evenodd"
              d="M9 7V2.221a2 2 0 0 0-.5.365L4.586 6.5a2 2 0 0 0-.365.5H9Zm2 0V2h7a2 2 0 0 1 2 2v9.293l-2-2a1 1 0 0 0-1.414 1.414l.293.293h-6.586a1 1 0 1 0 0 2h6.586l-.293.293A1 1 0 0 0 18 16.707l2-2V20a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V9h5a2 2 0 0 0 2-2Z"
              clip-rule="evenodd" />
          </svg>
        </div>
        <h3 class="mb-2 text-xl font-bold">Data Export</h3>
        <p class="text-gray-500">Download CRM data as CSV or PDF files.</p>
      </div>
    </div>
  </div>
</section>

templates/includes/footer.html
{% load static %}
<footer class="bg-gray-800 text-white py-4 px-4 absolute bottom-0 w-full">
  <div class="container mx-auto flex flex-col md:flex-row justify-between items-center space-y-4 md:space-y-0">

    <div class="flex items-end gap-1">
      {% include 'analytics/likes.html' %}
    </div>

    <div class="flex items-end gap-1">
      {% include 'analytics/live_users.html' %}
    </div>

    <div class="flex space-x-4 items-end">
      <a href="https://github.com/Shreehar-KE/django-crm" target="_blank" class="hover:text-gray-300">
        <img class="h-6" src="{% static 'img/github-dark.svg' %}" alt="GitHub" title="view source">
      </a>
      <a href="https://www.linkedin.com/posts/shreehar-ke_buildinpublic-devlog-django-activity-7260159084438425600-c3aT" target="_blank"
        class="hover:text-gray-300">
        <img class="h-6" src="{% static 'img/linkedin.svg' %}" alt="LinkedIn" title="follow devlog">
      </a>
      <a href="https://shreehar-ke.github.io/" target="_blank" title="visit portfolio"
        class="text-xl/none font-bold text-white [&>span]:text-primary-500"><span>Shree</span>har</a>
      </a>
    </div>

  </div>
</footer>

templates/includes/header.html
{% load static %}
<header x-data="{ mobileNavOpen: false }"
  class="md:flex items-center justify-between [&>*]:px-8 h-16 bg-gray-800 text-white sticky top-0 z-50 select-none">
  <div class="flex items-center justify-between h-16">
    <logo>
      <a class="flex items-center gap-1" href="{% url 'a_contacts:home' %}">
        <img class="h-6" src="{% static 'img/logo.svg' %}" alt="infinity-logo">
        <span class="font-sans font-extrabold">CRM</span>
      </a>
    </logo>
    <mobileicon class="md:hidden">
      <a @click="mobileNavOpen = !mobileNavOpen"
        class="size-12 flex items-center justify-center cursor-pointer select-none hover:bg-gray-700 rounded-lg">
        <img x-show="!mobileNavOpen" class="size-6" src="{% static 'img/menu.svg' %}" alt="hamburger-menu">
        <img x-show="mobileNavOpen" x-cloak class="size-6" src="{% static 'img/close.svg' %}" alt="close-button">
      </a>
    </mobileicon>
  </div>
  <nav x-show="mobileNavOpen" x-cloak
    class="md:!block bg-gray-800 h-screen w-screen md:h-auto md:w-auto -mt-26 md:mt-0 absolute md:relative z-[-1]"
    x-transition:enter="duration-300 ease-out" x-transition:enter-start="opacity-0 -translate-y-96"
    x-transition:enter-end="opacity-100 translate-y-0" x-transition:leave="duration-300 ease-out"
    x-transition:leave-start="opacity-100 translate-y-0" x-transition:leave-end="opacity-0 -translate-y-96">
    <ul class="flex items-center flex-col md:flex-row gap-8 md:gap-2 justify-center h-full -translate-y-10 md:translate-y-0">
      {% if user.is_authenticated %}
      <li>
        <a class="select-none navitem" href="{% url 'accounts:employee-list' %}">
          All Users
        </a>
      </li>
      <li>
        <a class="select-none navitem" href="{% url 'a_contacts:event-list' %}">
          Events
        </a>
      </li>
      <li x-data="{ dropdownOpen: false}" class="relative">
        <a @click="dropdownOpen = !dropdownOpen" @click.away="dropdownOpen = false" class="select-none navitem">
          Export
          <img x-bind:class="dropdownOpen ? 'rotate-180 duration-300' : '' " class="w-4 mt-1" src="{% static 'img/expand-arrow.svg' %}"
            alt="">
        </a>
        <div x-show="dropdownOpen" x-cloak class="absolute top-14 right-0 bg-gray-50 text-gray-700 shadow rounded-lg w-40 p-2 z-20"
          x-transition:enter="duration-300 ease-out" x-transition:enter-start="opacity-0 -translate-y-5 scale-90"
          x-transition:enter-end="opacity-100 translate-y-0 scale-100" x-transition:leave="duration-300 ease-out"
          x-transition:leave-start="opacity-100 translate-y-0" x-transition:leave-end="opacity-0 -translate-y-5">
          <ul class="menulist [&>li:active]:bg-primary-200">
            <li><a id="export-csv" hx-get="{% url 'a_contacts:export-data-csv' %}" hx-swap="none">Export CSV</a></li>
            <li><a id="export-pdf" hx-get="{% url 'a_contacts:export-data-pdf' %}" hx-swap="none">Export PDF</a></li>
          </ul>
        </div>
      </li>
      {% endif %}
      <li x-data="{ dropdownOpen: false}" class="relative">
        <a @click="dropdownOpen = !dropdownOpen" @click.away="dropdownOpen = false" class="select-none navitem">
          <img class="h-6 outline-double outline-gray-700 rounded-full object-cover bg-primary-500" src="{% static 'img/user.svg'%}"
            alt="user-avatar">
          <span class="max-w-20 truncate">
            {% if user.is_authenticated %}
            {{ user.username }}
            {% else %}
            Guest User
            {% endif %}
          </span>
          <img x-bind:class="dropdownOpen ? 'rotate-180 duration-300' : '' " class="w-4 mt-1" src="{% static 'img/expand-arrow.svg' %}"
            alt="">
        </a>
        <div x-show="dropdownOpen" x-cloak class="absolute top-14 right-0 bg-gray-50 text-gray-700 shadow rounded-lg w-40 p-2 z-20"
          x-transition:enter="duration-300 ease-out" x-transition:enter-start="opacity-0 -translate-y-5 scale-90"
          x-transition:enter-end="opacity-100 translate-y-0 scale-100" x-transition:leave="duration-300 ease-out"
          x-transition:leave-start="opacity-100 translate-y-0" x-transition:leave-end="opacity-0 -translate-y-5">
          {% if user.is_authenticated %}
          <ul class="menulist">
            <li><a href="{% url 'accounts:employee-detail' user.pk %}">My Profile</a></li>
            <li class="hover:bg-red-200"><a href="{% url 'account_logout' %}">Log Out</a></li>
          </ul>
          {% else %}
          <ul class="menulist">
            <li><a href="{% url 'account_login' %}">Log In</a></li>
            <li class="hover:bg-green-200"><a href="{% url 'account_signup' %}">Sign Up</a></li>
          </ul>
          {% endif %}
        </div>
      </li>
    </ul>
  </nav>
</header>

templates/includes/hero.html
{% load static %}
<hero class="grid bg-gray-700 text-white">
  <div class="py-8 px-4 mx-auto max-w-screen-xl text-center lg:py-16 lg:px-12">
    <h1 class="mb-4 text-4xl font-extrabold tracking-tight leading-none md:text-5xl lg:text-6xl">Django CRM</h1>
    <p class="mb-8 text-lg font-normal lg:text-xl sm:px-16 xl:px-48">Manage and Track your customers with ease</p>
    <a href="{% url 'a_contacts:contact-create' %}" class="w-auto justify-center inline-flex items-center px-4 py-2 text-sm font-medium text-center text-white bg-primary-500 rounded-lg hover:bg-primary-700
          select-none transition-transform duration-300 active:scale-95">Get Started
      <svg class="ml-2 -mr-1 w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd"
          d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
          clip-rule="evenodd"></path>
      </svg>
    </a>
  </div>
</hero>

templates/includes/table.html
<table class="w-full text-sm text-left text-gray-500 mb-24">
  <thead class="text-xs text-gray-700 uppercase bg-gray-200 ">
    <tr>
      <th scope="col" class="hidden sm:table-cell px-4 py-3 select-none">S.No.</th>
      <th scope="col" id="table" class="px-4 py-3 select-none">ID</th>
      <th scope="col" class="px-4 py-3 select-none">Name</th>
      <th scope="col" class="hidden sm:table-cell px-4 py-3 select-none">Email</th>
      <th scope="col" class="hidden lg:table-cell px-4 py-3 select-none">Location</th>
      <th scope="col" class="px-4 py-3 select-none">Type</th>
      <th scope="col" class="px-4 py-3">
        <span class="sr-only">Actions</span>
      </th>
    </tr>
  </thead>
  <tbody id="table-body">
    {% include 'partials/table_row.html' %}
  </tbody>
</table>

templates/includes/toast.html
<div hx-swap-oob="true" id="toast" x-data="{dismissed: false}" x-show="!dismissed" x-init="setTimeout(() => dismissed=true, 5000)"
  x-transition:enter="duration-1000 ease-out" x-transition:enter-start="opacity-0 -translate-y-5 scale-90"
  x-transition:enter-end="opacity-100 translate-y-0 scale-100" x-transition:leave="duration-1000 ease-out"
  x-transition:leave-start="opacity-100 translate-y-0" x-transition:leave-end="opacity-0 -translate-y-5">
  {% if messages %}
  {% for message in messages %}
  {% if message.tags == 'success' %}
  <div id="toast-success"
    class="fixed bottom-16 right-5 z-[100] flex items-center w-full max-w-xs p-2 text-gray-500 bg-slate-50 rounded-lg shadow" role="alert">
    <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 text-green-500 bg-green-100 rounded-lg">
      <svg class=" w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
        <path
          d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z" />
      </svg>
      <span class="sr-only">Check icon</span>
    </div>
    <div class="ms-3 text-sm font-normal">{{ message }}</div>
    <button type="button" @click="dismissed=true"
      class="ms-auto -mx-1.5 -my-1.5 bg-slate-50 text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-red-100 inline-flex items-center justify-center h-8 w-8"
      data-dismiss-target="#toast-success" aria-label="Close">
      <span class="sr-only">Close</span>
      <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
      </svg>
    </button>
  </div>
  {% elif message.tags == 'error' %}
  <div id="toast-danger"
    class="fixed bottom-16 right-5 z-[100] flex items-center w-full max-w-xs p-2 text-gray-500 bg-slate-50 rounded-lg shadow" role="alert">
    <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 text-red-500 bg-red-100 rounded-lg">
      <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
        <path
          d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 11.793a1 1 0 1 1-1.414 1.414L10 11.414l-2.293 2.293a1 1 0 0 1-1.414-1.414L8.586 10 6.293 7.707a1 1 0 0 1 1.414-1.414L10 8.586l2.293-2.293a1 1 0 0 1 1.414 1.414L11.414 10l2.293 2.293Z" />
      </svg>
      <span class="sr-only">Error icon</span>
    </div>
    <div class="ms-3 text-sm font-normal">{{ message }}</div>
    <button type="button" @click="dismissed=true"
      class="ms-auto -mx-1.5 -my-1.5 bg-slate-50 text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-red-100 inline-flex items-center justify-center h-8 w-8"
      data-dismiss-target="#toast-danger" aria-label="Close">
      <span class="sr-only">Close</span>
      <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
      </svg>
    </button>
  </div>
  {% elif message.tags == 'warning' %}
  <div id="toast-warning"
    class="fixed bottom-16 right-5 z-[100] flex items-center w-full max-w-xs p-2 text-gray-500 bg-slate-50 rounded-lg shadow" role="alert">
    <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 text-orange-500 bg-orange-100 rounded-lg">
      <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
        <path
          d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM10 15a1 1 0 1 1 0-2 1 1 0 0 1 0 2Zm1-4a1 1 0 0 1-2 0V6a1 1 0 0 1 2 0v5Z" />
      </svg>
      <span class="sr-only">Warning icon</span>
    </div>
    <div class="ms-3 text-sm font-normal">{{ message }}</div>
    <button type="button" @click="dismissed=true"
      class="ms-auto -mx-1.5 -my-1.5 bg-slate-50 text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-red-100 inline-flex items-center justify-center h-8 w-8"
      data-dismiss-target="#toast-warning" aria-label="Close">
      <span class="sr-only">Close</span>
      <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
      </svg>
    </button>
  </div>
  {% elif message.tags == 'info' %}
  <div id="toast-info"
    class="fixed bottom-16 right-5 z-[100] flex items-center w-full max-w-xs p-2 text-gray-500 bg-slate-50 rounded-lg shadow" role="alert">
    <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 text-blue-500 bg-blue-100 rounded-lg">
      <svg class="w-5 h-5 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24"
        fill="blue" viewBox="0 0 24 24">
        <path fill-rule="evenodd"
          d="M2 12C2 6.477 6.477 2 12 2s10 4.477 10 10-4.477 10-10 10S2 17.523 2 12Zm9.408-5.5a1 1 0 1 0 0 2h.01a1 1 0 1 0 0-2h-.01ZM10 10a1 1 0 1 0 0 2h1v3h-1a1 1 0 1 0 0 2h4a1 1 0 1 0 0-2h-1v-4a1 1 0 0 0-1-1h-2Z"
          clip-rule="evenodd" />
      </svg>
      <span class="sr-only">Info icon</span>
    </div>
    <div class="ms-3 text-sm font-normal">{{ message }}</div>
    <button type="button" @click="dismissed=true"
      class="ms-auto -mx-1.5 -my-1.5 bg-slate-50 text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-red-100 inline-flex items-center justify-center h-8 w-8"
      data-dismiss-target="#toast-warning" aria-label="Close">
      <span class="sr-only">Close</span>
      <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6" />
      </svg>
    </button>
  </div>
  {% endif %}
  {% endfor %}
  {% endif %}
</div>